name: Ubuntu_shell
on: [push]
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    - name: installation
      continue-on-error: true
      run: |
        sudo apt-get remove account-plugin-facebook account-plugin-flickr account-plugin-jabber account-plugin-salut account-plugin-twitter account-plugin-windows-live account-plugin-yahoo aisleriot brltty duplicity empathy empathy-common example-content gnome-accessibility-themes gnome-contacts gnome-mahjongg gnome-mines gnome-orca gnome-screensaver gnome-sudoku gnome-video-effects gnomine landscape-common libreoffice-avmedia-backend-gstreamer libreoffice-base-core libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw libreoffice-gnome libreoffice-gtk libreoffice-impress libreoffice-math libreoffice-ogltrans libreoffice-pdfimport libreoffice-style-galaxy libreoffice-style-human libreoffice-writer libsane libsane-common mcp-account-manager-uoa python3-uno rhythmbox rhythmbox-plugins rhythmbox-plugin-zeitgeist sane-utils shotwell shotwell-common telepathy-gabble, telepathy-haze, telepathy-idle, telepathy-indicator telepathy-logger telepathy-mission-control-5, telepathy-salut totem totem-common totem-plugins printer-driver-brlaser printer-driver-foo2zjs printer-driver-foo2zjs-common printer-driver-m2300w printer-driver-ptouch printer-driver-splix
        sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo add-apt-repository ppa:qbittorrent-team/qbittorrent-stable
        sudo apt-get install qbittorrent-nox
        sudo snap install ngrok
    - uses: actions/checkout@v2
    - run: source echo.sh
      
    - name: Setup tmate session
      continue-on-error: true
      uses: mxschmitt/action-tmate@master  
      
    - name: Git-config
      continue-on-error: true
      run: |
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           git config --global user.name "meeker0"
           git config --global user.email "wcabrera4@student.mtsac.edu"         
           sudo -E apt-get clean 
           sudo apt install -y expect
           
    - name: Loop workflow
      run: |
        git clone https://${{ secrets.GHUSER }}:${{ secrets.GHPASS }}@github.com/${{ secrets.GHUSER }}/ssh_control_git.git loop
        cd loop
        echo "1" >> loop.txt
        git add loop.txt
        git commit -m "Workflow : Loop" 
